
import type { Metadata } from "next";
import { Playfair, Roboto, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";
import MenuButton from "./components/menu/menuButton";
import MenuOverlay from "./components/menu/menuOverlay";
import HeaderWrapper from "./components/HeaderWrapper";
import { Providers } from "./providers/providers";



const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });
const playfair = Playfair({ subsets: ["latin"], variable: "--font-playfair" });

export const metadata: Metadata = {
  title: "Rasmus Ferst",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${geistMono.variable} ${playfair.variable} antialiased`}>
        {/* Pass toggleMenu to Header so MenuButton can toggle */}
        <Providers>
          <HeaderWrapper>{children}</HeaderWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
